# Generated by Django 3.2 on 2022-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='price',
        ),
        migrations.AddField(
            model_name='budget',
            name='max_price',
            field=models.BigIntegerField(default=32, verbose_name='maximum price of project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='min_price',
            field=models.BigIntegerField(default=1, verbose_name='minimum price of project'),
            preserve_default=False,
        ),
    ]
