# Generated by Django 3.2 on 2022-08-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220825_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.AlterModelTable(
            name='projectfile',
            table='project_file',
        ),
        migrations.AlterModelTable(
            name='projectskill',
            table='project_skill',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
        migrations.AlterModelTable(
            name='userbid',
            table='user_bid',
        ),
    ]
