# Generated by Django 3.2 on 2022-08-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_portfolio_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': ('portfolio',), 'verbose_name_plural': 'portfolios'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(upload_to='portfolio/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='accounts.user', verbose_name='belong to'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='accounts.user', verbose_name='followed by'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.user', verbose_name='followed to'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bids_left',
            field=models.SmallIntegerField(default=5, verbose_name='bids left'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_kyc',
            field=models.BooleanField(default=False, verbose_name='KYC'),
        ),
    ]
