# Generated by Django 5.1.4 on 2024-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='chatsaeed', max_length=100),
            preserve_default=False,
        ),
    ]
